# Generated by Django 2.2.13 on 2020-08-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_auto_20200817_0437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='alcohol',
        ),
        migrations.AddField(
            model_name='drink',
            name='alcohols',
            field=models.ManyToManyField(blank=True, related_name='drinks', to='drinks.Alcohol'),
        ),
    ]
