# Generated by Django 2.2.13 on 2020-08-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0006_drink_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/drinks/%Y/%m/%d/'),
        ),
    ]
