# Generated by Django 2.2.13 on 2020-08-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0007_auto_20200817_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='drink',
            field=models.ManyToManyField(blank=True, related_name='ingredients', to='drinks.Drink'),
        ),
        migrations.DeleteModel(
            name='DrinkIngredient',
        ),
    ]
