# Generated by Django 2.2.13 on 2020-08-18 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0008_auto_20200818_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='drink',
        ),
        migrations.CreateModel(
            name='DrinkIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='drinks.Drink')),
                ('ingredient', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='drinks.Ingredient')),
            ],
            options={
                'verbose_name': 'drink ingredient',
                'verbose_name_plural': 'drink ingredients',
            },
        ),
        migrations.AddField(
            model_name='drink',
            name='ingredients',
            field=models.ManyToManyField(blank=True, through='drinks.DrinkIngredient', to='drinks.Ingredient'),
        ),
    ]
